const cities = [
    "Airdrie, AB",
    "Grande Prairie, AB",
    "Red Deer, AB",
    "Beaumont, AB",
    "Hanna, AB",
    "St. Albert, AB",
    "Bonnyville, AB",
    "Hinton, AB",
    "Spruce Grove, AB",
    "Brazeau, AB",
    "Irricana, AB",
    "Strathcona County, AB",
    "Breton, AB",
    "Lacombe, AB",
    "Strathmore, AB",
    "Calgary, AB",
    "Leduc, AB",
    "Sylvan Lake, AB",
    "Camrose, AB",
    "Lethbridge, AB",
    "Swan Hills, AB",
    "Canmore, AB",
    "McLennan, AB",
    "Taber, AB",
    "Didzbury, AB",
    "Medicine Hat, AB",
    "Turner Valley, AB",
    "Drayton Valley, AB",
    "Olds, AB",
    "Vermillion, AB",
    "Edmonton, AB",
    "Onoway, AB",
    "Wood Buffalo, AB",
    "Ft. Saskatchewan, AB",
    "Provost, AB",
    "Burnaby, BC",
    "Lumby, BC",
    "City of Port Moody, BC",
    "Cache Creek, BC",
    "Maple Ridge, BC",
    "Prince George, BC",
    "Castlegar, BC",
    "Merritt, BC",
    "Prince Rupert, BC",
    "Chemainus, BC",
    "Mission, BC",
    "Richmond, BC",
    "Chilliwack, BC",
    "Nanaimo, BC",
    "Saanich, BC",
    "Clearwater, BC",
    "Nelson, BC",
    "Sooke, BC",
    "Colwood, BC",
    "New Westminster, BC",
    "Sparwood, BC",
    "Coquitlam, BC",
    "North Cowichan, BC",
    "Surrey, BC",
    "Cranbrook, BC",
    "North Vancouver, BC",
    "Terrace, BC",
    "Dawson Creek, BC",
    "Tumbler, BC",
    "Delta, BC",
    "Osoyoos, BC",
    "Vancouver, BC",
    "Fernie, BC",
    "Parksville, BC",
    "Invermere, BC",
    "Peace River, BC",
    "Vernon, BC",
    "Kamloops, BC",
    "Penticton, BC",
    "Victoria, BC",
    "Kaslo, BC",
    "Port Alberni, BC",
    "Whistler, BC",
    "Langley, BC",
    "Port Hardy, BC",
    "Birtle, MB",
    "Flin Flon, MB",
    "Swan River, MB",
    "Brandon, MB",
    "Snow Lake, MB",
    "The Pas, MB",
    "Cranberry Portage, MB",
    "Steinbach, MB",
    "Thompson, MB",
    "Dauphin, MB",
    "Stonewall, MB",
    "Winnipeg, MB",
    "Cap-Pele, NB",
    "Miramichi, NB",
    "Saint John, NB",
    "Fredericton, NB",
    "Moncton, NB",
    "Saint Stephen, NB",
    "Grand Bay-Westfield, NB",
    "Oromocto, NB",
    "Shippagan, NB",
    "Grand Falls, NB",
    "Port Elgin, NB",
    "Sussex, NB",
    "Memramcook, NB",
    "Sackville, NB",
    "Tracadie-Sheila, NB",
    "Argentia, NL",
    "Corner Brook, NL",
    "Paradise, NL",
    "Bishop's Falls, NL",
    "Labrador City, NL",
    "Portaux Basques, NL",
    "Botwood, NL",
    "Mount Pearl, NL",
    "St. John's, NL",
    "Brigus, NL",
    "Town of Hay River, NT",
    "Town of Inuvik, NT",
    "Yellowknife, NT",
    "Amherst, NS",
    "Hants County, NS",
    "Pictou, NS",
    "Annapolis, NS",
    "Inverness County, NS",
    "Pictou County, NS",
    "Argyle, NS",
    "Kentville, NS",
    "Queens, NS",
    "Baddeck, NS",
    "County of Kings, NS",
    "Richmond, NS",
    "Bridgewater, NS",
    "Lunenburg, NS",
    "Shelburne, NS",
    "Cape Breton, NS",
    "Lunenburg County, NS",
    "Stellarton, NS",
    "Chester, NS",
    "Mahone Bay, NS",
    "Truro, NS",
    "Cumberland County, NS",
    "New Glasgow, NS",
    "Windsor, NS",
    "East Hants, NS",
    "New Minas, NS",
    "Yarmouth, NS",
    "Halifax, NS",
    "Parrsboro, NS",
    "Ajax, ON",
    "Halton, ON",
    "Peterborough, ON",
    "Atikokan, ON",
    "Halton Hills, ON",
    "Pickering, ON",
    "Barrie, ON",
    "Hamilton, ON",
    "Port Bruce, ON",
    "Belleville, ON",
    "Port Burwell, ON",
    "Blandford-Blenheim, ON",
    "Hearst, ON",
    "Port Colborne, ON",
    "Blind River, ON",
    "Huntsville, ON",
    "Port Hope, ON",
    "Brampton, ON",
    "Ingersoll, ON",
    "Prince Edward, ON",
    "Brant, ON",
    "James, ON",
    "Quinte West, ON",
    "Brantford, ON",
    "Kanata, ON",
    "Renfrew, ON",
    "Brock, ON",
    "Kincardine, ON",
    "Richmond Hill, ON",
    "Brockville, ON",
    "King, ON",
    "Sarnia, ON",
    "Burlington, ON",
    "Kingston, ON",
    "Sault Ste. Marie, ON",
    "Caledon, ON",
    "Kirkland Lake, ON",
    "Scarborough, ON",
    "Cambridge, ON",
    "Kitchener, ON",
    "Scugog, ON",
    "Chatham-Kent, ON",
    "Larder Lake, ON",
    "Chesterville, ON",
    "Leamington, ON",
    "Smiths Falls, ON",
    "Clarington, ON",
    "Lennox-Addington, ON",
    "South-West Oxford, ON",
    "Cobourg, ON",
    "Lincoln, ON",
    "St. Catharines, ON",
    "Cochrane, ON",
    "Lindsay, ON",
    "St. Thomas, ON",
    "Collingwood, ON",
    "London, ON",
    "Stoney Creek, ON",
    "Cornwall, ON",
    "Loyalist Township, ON",
    "Stratford, ON",
    "Cumberland, ON",
    "Markham, ON",
    "Sudbury, ON",
    "Deep River, ON",
    "Metro Toronto, ON",
    "Temagami, ON",
    "Dundas, ON",
    "Merrickville, ON",
    "Thorold, ON",
    "Durham, ON",
    "Milton, ON",
    "Thunder Bay, ON",
    "Dymond, ON",
    "Nepean, ON",
    "Tillsonburg, ON",
    "Ear Falls, ON",
    "Newmarket, ON",
    "Timmins, ON",
    "East Gwillimbury, ON",
    "Niagara, ON",
    "Toronto, ON",
    "East Zorra-Tavistock, ON",
    "Niagara Falls, ON",
    "Uxbridge, ON",
    "Elgin, ON",
    "Niagara-on-the-Lake, ON",
    "Vaughan, ON",
    "Elliot Lake, ON",
    "North Bay, ON",
    "Wainfleet, ON",
    "Flamborough, ON",
    "North Dorchester, ON",
    "Wasaga Beach, ON",
    "Fort Erie, ON",
    "North Dumfries, ON",
    "Waterloo, ON",
    "Fort Frances, ON",
    "North York, ON",
    "Gananoque, ON",
    "Norwich, ON",
    "Welland, ON",
    "Georgina, ON",
    "Oakville, ON",
    "Wellesley, ON",
    "Glanbrook, ON",
    "Orangeville, ON",
    "West Carleton, ON",
    "Gloucester, ON",
    "Orillia, ON",
    "West Lincoln, ON",
    "Goulbourn, ON",
    "Osgoode, ON",
    "Whitby, ON",
    "Gravenhurst, ON",
    "Oshawa, ON",
    "Wilmot, ON",
    "Grimsby, ON",
    "Ottawa, ON",
    "Windsor, ON",
    "Guelph, ON",
    "Ottawa-Carleton, ON",
    "Woolwich, ON",
    "Haldimand-Norfork, ON",
    "Owen Sound, ON",
    "York, ON",
    "Alberton, PE",
    "Montague, PE",
    "Stratford, PE",
    "Charlottetown, PE",
    "Souris, PE",
    "Summerside, PE",
    "Cornwall, PE",
    "Alma, QC",
    "Fleurimont, QC",
    "Longueuil, QC",
    "Amos, QC",
    "Gaspe, QC",
    "Marieville, QC",
    "Anjou, QC",
    "Gatineau, QC",
    "Mount Royal, QC",
    "Aylmer, QC",
    "Hull, QC",
    "Montreal, QC",
    "Beauport, QC",
    "Joliette, QC",
    "Bromptonville, QC",
    "Jonquiere, QC",
    "Brosssard, QC",
    "Lachine, QC",
    "Quebec City, QC",
    "Chateauguay, QC",
    "Lasalle, QC",
    "Saint-Leonard, QC",
    "Chicoutimi, QC",
    "Laurentides, QC",
    "Sherbrooke, QC",
    "Coaticook, QC",
    "LaSalle, QC",
    "Sorel, QC",
    "Laval, QC",
    "Thetford Mines, QC",
    "Dorval, QC",
    "Lennoxville, QC",
    "Victoriaville, QC",
    "Drummondville, QC",
    "Levis, QC",
    "Avonlea, SK",
    "Melfort, SK",
    "Swift Current, SK",
    "Colonsay, SK",
    "Nipawin, SK",
    "Tisdale, SK",
    "Craik, SK",
    "Prince Albert, SK",
    "Unity, SK",
    "Creighton, SK",
    "Regina, SK",
    "Weyburn, SK",
    "Eastend, SK",
    "Saskatoon, SK",
    "Wynyard, SK",
    "Esterhazy, SK",
    "Shell Lake, SK",
    "Yorkton, SK",
    "Gravelbourg, SK",
    "Carcross, YT",
    "Whitehorse, YT"
  ]