// All currently supported cities
const cities = [
    "Calgary, AB",
    "Edmonton, AB",
    "Burnaby, BC",
    "Coquitlam, BC",
    "Langley, BC",
    "Richmond, BC",
    "Surrey, BC",
    "Vancouver, BC",
    "Victoria, BC",
    "Brandon, MB",
    "Carman, MB",
    "Steinbach, MB",
    "Winnipeg, MB",
    "Dieppe, NB",
    "Fredericton, NB",
    "Saint John, NB",
    "Hamilton, ON",
    "Kitchener, ON",
    "London, ON",
    "Mississauga, ON",
    "Ottawa, ON",
    "Toronto, ON",
    "Waterloo, ON",
    "Windsor, ON",
    "Cornwall, PE",
    "Summerside, PE",
    "Moose Jaw, SK",
    "North Battleford, SK",
    "Regina, SK",
    "Saskatoon, SK",
    "Swift Current, SK",
    "Weyburn, SK",
];
