// All currently supported cities
const cities = [
  'Calgary, AB',
  'Edmonton, AB',
  'Grand Prairie, AB',
  'Burnaby, BC',
  'Coquitlam, BC',
  'Langley, BC',
  'Richmond, BC',
  'Surrey, BC',
  'Vancouver, BC',
  'Victoria, BC',
  'Brandon, MB',
  'Carman, MB',
  'Niverville, MB',
  'Steinbach, MB',
  'Winnipeg, MB',
  'Dieppe, NB',
  'Edmunston, NB',
  'Fredericton, NB',
  'Moncton, NB',
  'Quispamsis, NB',
  'Saint John, NB',
  'Hamilton, ON',
  'London, ON',
  'Mississauga, ON',
  'Ottawa, ON',
  'Toronto, ON',
  'Windsor, ON',
  'Charlottetown, PE',
  'Cornwall, PE',
  'Covehead, PE',
  'Mermaid, PE',
  'Stratford, PE',
  'Summerside, PE',
  'Moose Jaw, SK',
  'North Battleford, SK',
  'Regina, SK',
  'Saskatoon, SK',
  'Swift Current, SK',
  'Weyburn, SK',
  ]